/*
 * cfg_addr.h
 *
 *  Created on: 1 Mar 2022
 *      Author: muhammad.ahmad@georgekent.net
 */

#ifndef CFG_ADDR_H_
#define CFG_ADDR_H_

#define CFG_MCU_FLASH_SIZE				0x40000//(FLASH_BANK_SIZE)/*256K bytes, 127 pages*/
#define CFG_PARTITION_0_SIZE			(4* FLASH_PAGE_SIZE)/*bootloader*///(4* FLASH_PAGE_SIZE)/*8192 bytes, 4 pages*/
#define CFG_PARTITION_CONFIG_SIZE		(6* FLASH_PAGE_SIZE)
#define CFG_PARTITION_0					0
#define CFG_PARTITION_1					1
#define CFG_PARTITION_2					2
#define CFG_PARTITION_CONFIG			3
#define CFG_PARTITION_SIZE				((CFG_MCU_FLASH_SIZE- (CFG_PARTITION_0_SIZE+ CFG_PARTITION_CONFIG_SIZE))/ 2)
#define CFG_PARTITION_1_ADDR  			(FLASH_BASE+ CFG_PARTITION_0_SIZE)			/*ORIGIN = 0x8000000+ p0, LENGTH = 122K- p0*/
#define CFG_PARTITION_2_ADDR 			(CFG_PARTITION_1_ADDR+ CFG_PARTITION_SIZE)	/*ORIGIN = 0x0801E800+ p0, LENGTH = 122K- p0*/
#define CFG_PARTITION_CONFIG_ADDR		(CFG_PARTITION_2_ADDR+ CFG_PARTITION_SIZE)

#define CFG_CONFIG_ADDRESS_FLASH		(CFG_PARTITION_CONFIG_ADDR)
#define CFG_CONFIG_ADDRESS_SYSTEM		(CFG_CONFIG_ADDRESS_FLASH+ sizeof(Flash_t))
#define CFG_CONFIG_ADDRESS_FAILSAFE		(CFG_CONFIG_ADDRESS_SYSTEM+ sizeof(System_t))
#define CFG_CONFIG_ADDRESS_DIAG			(CFG_CONFIG_ADDRESS_FAILSAFE+ sizeof(FAILSAFE_t))
#define CFG_CONFIG_ADDRESS_PULSER		(CFG_CONFIG_ADDRESS_DIAG+ sizeof(DIAG_t))
#define CFG_CONFIG_ADDRESS_LOG			(CFG_CONFIG_ADDRESS_PULSER+ sizeof(PULSER_t))
#define CFG_CONFIG_ADDRESS_SENSOR		(CFG_CONFIG_ADDRESS_LOG+ sizeof(LOG_t))
#define CFG_CONFIG_ADDRESS_ALARM		(CFG_CONFIG_ADDRESS_SENSOR+ sizeof(SENSOR_t))
#define CFG_CONFIG_ADDRESS_NBIOT		(CFG_CONFIG_ADDRESS_ALARM+ sizeof(ALARM_t))
#define CFG_CONFIG_ADDRESS_END			(CFG_CONFIG_ADDRESS_NBIOT+ sizeof(NBIOT_t))


#endif /* CFG_ADDR_H_ */
