#ifndef MODULE_CONFIG_H
#define MODULE_CONFIG_H

#define ALARM_MODULE_ENABLED       1
#define DEBUG_MODULE_ENABLED       1
#define BOOTLOADERS_MODULE_ENABLED 0
#define CONFIG_MODULE_ENABLED      0
#define DIAGNOSIS_MODULE_ENABLED   0
#define DRIVERS_MODULE_ENABLED     0
#define FAILSAFE_MODULE_ENABLED    0
#define IOCTRL_MODULE_ENABLED      0
#define LOGGER_MODULE_ENABLED      0
#define MESSAGE_MODULE_ENABLED     0
#define NETWORK_MODULE_ENABLED     0
#define PROTOCOLS_MODULE_ENABLED   0
#define RTOS_MODULE_ENABLED        0
#define SECURITY_MODULE_ENABLED    0
#define STORAGE_MODULE_ENABLED     0
#define SYSTEM_MODULE_ENABLED      0

#endif // MODULE_CONFIG_H
